### ISSUE TITLE
playback logic is confusing.

### ISSUE THREAD

**Issue by ZenaMel** [Mnaukal/virtual-loop-pedal#5]
Please take a look at this short demonstration. I can't get a clean loop. I get double-sounds on the beginning of the next bar. The latency is not a problem since I can tweak that. It's only about the "loop-leak".

[Demo](https://youtu.be/azckZNseaEk)

**Comment by Mnaukal** [comment]
Yeah, thanks for pointing that out. It this seems like the same issue as #2. Unfortunately, this was a school project created over two years ago and I don't have time to work on this project now or in near future.

**Comment by ZenaMel** [comment]
@Mnaukal would you mind `archiving` the repository then? Otherwise people like me stumble upon it thinking it is still kinda active when in fact the maintainer has abandoned the project.

`archiving` a repository is meant for exactly this scenario.
